import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import Poppins font from Google Fonts using next/font
import { Poppins } from "next/font/google";

// Load Poppins font
const poppins = Poppins({
    variable: "--font-poppins", // Custom variable for global usage
    subsets: ["latin"], // Ensure Latin subset is available
    weight: ["300", "400", "600"], // You can choose specific weights (300 for thin, 400 for normal, 600 for bold)
});

// Load Geist and Geist_Mono fonts
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "John Harold",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            {/* No need to manually link the Poppins font in <head> since next/font handles this */}
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`} // Applying fonts here
        >
        {children}
        </body>
        </html>
    );
}
